import './styles.css';
import './desktop.css';
import { adminApi, ApiError } from './api';

type View='dashboard'|'organizations'|'users'|'loans'|'documents'|'risk'|'disputes'|'audit';
const app=document.querySelector<HTMLDivElement>('#app')!;
let session:any=null;
let state:any={dashboard:null,organizations:[],users:[],loans:[],documents:[],risk:[],disputes:[],audit:[]};
const nav:Array<[View,string,string]>=[['dashboard','Visión general','⌂'],['organizations','Organizaciones','O'],['users','Usuarios','U'],['loans','Créditos','C'],['documents','Documentos','D'],['risk','Riesgo','!'],['disputes','Disputas','∆'],['audit','Auditoría','A']];
const brl=(minor:number=0)=>(minor/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]!));
const err=(e:unknown)=>e instanceof ApiError?`${e.message}${e.requestId?` · ${e.requestId}`:''}`:'No fue posible completar la operación.';
const badge=(text:string)=>`<span class="badge ${['ACTIVE','ACTIVA','APPROVED','VERIFIED','RESOLVED'].includes(text)?'ok':['PENDING','PENDING_REVIEW','NEEDS_CORRECTION','OPEN','INVESTIGATING'].includes(text)?'warn':''}">${esc(text)}</span>`;

function loginScreen(message=''){
  app.innerHTML=`<div class="layout"><main class="main"><section class="content"><div class="page-head"><div><p class="eyebrow">CLAVOS CONTROL</p><h1>Acceso administrativo</h1><p>Solo cuentas con rol de plataforma autorizado pueden ingresar.</p></div></div><article class="panel" style="max-width:520px">${message?`<div class="case"><div><b>Error de acceso</b><p>${esc(message)}</p></div></div>`:''}<form id="loginForm"><label>Correo electrónico<input id="email" type="email" autocomplete="username" placeholder="admin@clavosbrasil.com" required></label><label>Contraseña<input id="password" type="password" autocomplete="current-password" placeholder="Tu contraseña" required></label><button class="primary">Ingresar</button></form></article></section></main></div>`;
  document.querySelector<HTMLFormElement>('#loginForm')!.onsubmit=async e=>{e.preventDefault();try{session=await adminApi.login((document.querySelector<HTMLInputElement>('#email')!).value,(document.querySelector<HTMLInputElement>('#password')!).value);if(!String(session.role||'').includes('ADMIN')&&!['SUPERADMIN','RISK_ANALYST','DOCUMENT_ANALYST','SUPPORT_AGENT'].includes(session.role))throw new Error('Esta cuenta no tiene acceso administrativo.');await loadAll();render('dashboard')}catch(e){loginScreen(err(e))}};
}

function shell(view:View,content:string){return `<div class="layout"><aside class="sidebar"><div class="brand"><div class="brandmark">CB</div><div><strong>Clavos Control</strong><small>Administración de plataforma</small></div></div><nav>${nav.map(([id,label,icon])=>`<button data-view="${id}" class="navitem ${view===id?'active':''}"><span>${icon}</span>${label}</button>`).join('')}</nav><div class="admin-card"><div class="avatar">${esc((session?.user?.full_name||'AD').split(' ').slice(0,2).map((x:string)=>x[0]).join(''))}</div><div><b>${esc(session?.user?.full_name||'Administrador')}</b><small>${esc(session?.role||'')}</small></div></div></aside><main class="main"><header class="topbar"><div class="search"><span>⌕</span><input placeholder="Buscar CPF, usuario, crédito, organización..."></div><div class="top-actions"><span class="env">LIVE API</span><button class="iconbtn" id="refresh">↻</button><button class="iconbtn" id="logout">×</button></div></header><section class="content">${content}</section></main></div>`}
const metric=(label:string,value:string,detail:string,tone='')=>`<article class="metric ${tone}"><small>${label}</small><strong>${value}</strong><span>${detail}</span></article>`;

async function loadAll(){
  const [dashboard,organizations,users,loans,documents,risk,disputes,audit]=await Promise.all([
    adminApi.dashboard(),adminApi.organizations(),adminApi.users(),adminApi.loans(),adminApi.documents(),adminApi.riskCases(),adminApi.disputes(),adminApi.audit()
  ]);
  state={dashboard,organizations:organizations.items||[],users:users.items||[],loans:loans.items||[],documents:documents.items||[],risk:risk.items||[],disputes:disputes.items||[],audit:audit.items||[]};
}

function dashboard(){const d=state.dashboard||{};const c=d.counts||{};const openRisk=state.risk.filter((r:any)=>['OPEN','INVESTIGATING'].includes(r.status)).length;return `<div class="page-head"><div><p class="eyebrow">CONTROL CENTER</p><h1>Visión general</h1><p>Datos reales consolidados de la API administrativa.</p></div></div><div class="metric-grid">${metric('Usuarios activos',String(c.active_users||0),'cuentas')}${metric('Organizaciones activas',String(c.active_organizations||0),'operaciones')}${metric('Personas registradas',String(c.persons||0),'perfiles')}${metric('Créditos activos',String(c.active_loans||0),'operaciones')}${metric('Capital en circulación',brl(d.portfolio?.principal_minor||0),'registrado')}${metric('Cobrado hoy',brl(d.today?.received_minor||0),`${d.today?.payments_count||0} pagos`,'good')}</div><div class="two-col"><article class="panel"><h2>Operación pendiente</h2><div class="ops"><div><b>${c.pending_documents||0}</b><span>Documentos pendientes</span></div><div><b>${c.open_disputes||0}</b><span>Disputas abiertas</span></div><div><b>${openRisk}</b><span>Casos de riesgo</span></div></div></article><article class="panel"><h2>Auditoría reciente</h2>${auditRows(state.audit.slice(0,4))}</article></div>`}

function table(title:string,headers:string[],rows:string[][]){return `<div class="page-head"><div><p class="eyebrow">OPERACIÓN</p><h1>${title}</h1><p>Datos cargados desde D1 por endpoint administrativo protegido.</p></div></div><article class="panel"><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">Sin registros.</td></tr>`}</tbody></table></div></article>`}

function organizations(){return table('Organizaciones',['ID','Organización','Región','Usuarios','Créditos','Capital','Estado'],state.organizations.map((o:any)=>[esc(o.id),esc(o.trade_name||o.legal_name),esc([o.city,o.state_region].filter(Boolean).join('/')),esc(o.users_count),esc(o.loans_count),brl(o.principal_minor),badge(o.status)]))}
function users(){return table('Usuarios',['ID','Nombre','Correo','Rol plataforma','Organizaciones','Último acceso','Estado'],state.users.map((u:any)=>[esc(u.id),esc(u.full_name),esc(u.email),esc(u.platform_role||'—'),esc(u.organizations_count),esc(u.last_seen_at||'—'),badge(u.status)]))}
function loans(){return table('Créditos',['ID','Tomador','Organización','Principal','Pagado','Saldo','Estado'],state.loans.map((l:any)=>[esc(l.id),esc(l.person_name),esc(l.organization_name),brl(l.principal_minor),brl(l.paid_minor),brl(Math.max(0,l.contractual_total_minor-l.paid_minor)),badge(l.status)]))}

function documents(){return `<div class="page-head"><div><p class="eyebrow">VERIFICACIÓN</p><h1>Documentos</h1><p>Archivos privados de R2. Visualización y decisión quedan auditadas.</p></div></div><article class="panel">${state.documents.length?state.documents.map((d:any)=>`<div class="case"><span class="docicon">${esc(d.document_type)}</span><div><b>${esc(d.person_name)}</b><p>${esc(d.organization_name||'Sin organización')} · ${esc(d.document_role)} · ${Math.round((d.size_bytes||0)/1024)} KB<br>${esc(d.original_filename||'archivo')}</p></div><div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end">${badge(d.review_status)}<button data-open-doc="${esc(d.id)}">Ver</button>${['PENDING','NEEDS_CORRECTION'].includes(d.review_status)?`<button data-review="${esc(d.id)}" data-decision="APPROVED">Aprobar</button><button data-review="${esc(d.id)}" data-decision="NEEDS_CORRECTION">Pedir corrección</button><button data-review="${esc(d.id)}" data-decision="REJECTED">Rechazar</button>`:''}</div></div>`).join(''):'<p>Sin documentos.</p>'}</article>`}

function risk(){return `<div class="page-head"><div><p class="eyebrow">RIESGO</p><h1>Central de riesgo</h1><p>Señales automáticas generadas por la operación y los documentos.</p></div></div><article class="panel">${state.risk.length?state.risk.map((r:any)=>`<div class="case"><span class="severity ${r.severity==='HIGH'||r.severity==='CRITICAL'?'high':'med'}">${esc(r.severity)}</span><div><b>${esc(r.id)} · ${esc(r.title)}</b><p>${esc(r.organization_name||'Sin organización')} · ${esc(r.person_name||'Sin persona')}<br>Tipo: ${esc(r.case_type)} · Estado: ${esc(r.status)}</p></div>${badge(r.status)}</div>`).join(''):'<p>Sin casos de riesgo abiertos.</p>'}</article>`}

function disputes(){return `<div class="page-head"><div><p class="eyebrow">COMPLIANCE</p><h1>Disputas</h1><p>Contestaciones registradas.</p></div></div><article class="panel">${state.disputes.length?state.disputes.map((d:any)=>`<div class="case"><span class="severity med">${esc(d.status)}</span><div><b>${esc(d.id)} · ${esc(d.person_name)}</b><p>${esc(d.reason)} · ${esc(d.organization_name||'')}</p></div></div>`).join(''):'<p>Sin disputas.</p>'}</article>`}
function auditRows(rows:any[]){return `<div class="audit-list">${rows.length?rows.map(a=>`<div><time>${esc(String(a.created_at||'').slice(11,16))}</time><span><b>${esc(a.actor_type)} ${esc(a.actor_id||'')}</b> ${esc(a.action)} · ${esc(a.target_type)} ${esc(a.target_id||'')}</span><em>${esc(a.organization_id||'GLOBAL')}</em></div>`).join(''):'<p>Sin eventos.</p>'}</div>`}
function audit(){return `<div class="page-head"><div><p class="eyebrow">SISTEMA</p><h1>Auditoría</h1><p>Registro de acciones operativas y administrativas.</p></div></div><article class="panel">${auditRows(state.audit)}</article>`}

function wire(view:View){document.querySelectorAll<HTMLElement>('[data-view]').forEach(el=>el.onclick=()=>render(el.dataset.view as View));document.querySelector<HTMLButtonElement>('#refresh')!.onclick=async()=>{await loadAll();render(view)};document.querySelector<HTMLButtonElement>('#logout')!.onclick=async()=>{await adminApi.logout().catch(()=>null);session=null;loginScreen()};document.querySelectorAll<HTMLButtonElement>('[data-open-doc]').forEach(btn=>btn.onclick=()=>window.open(adminApi.documentContentUrl(btn.dataset.openDoc!), '_blank','noopener,noreferrer'));document.querySelectorAll<HTMLButtonElement>('[data-review]').forEach(btn=>btn.onclick=async()=>{const reason=prompt('Motivo / observación de la revisión')||'';try{await adminApi.reviewDocument(btn.dataset.review!,{decision:btn.dataset.decision,reason});await loadAll();render('documents')}catch(e){alert(err(e))}})}
function render(view:View){let content='';if(view==='dashboard')content=dashboard();if(view==='organizations')content=organizations();if(view==='users')content=users();if(view==='loans')content=loans();if(view==='documents')content=documents();if(view==='risk')content=risk();if(view==='disputes')content=disputes();if(view==='audit')content=audit();app.innerHTML=shell(view,content);wire(view)}
async function bootstrap(){try{session=await adminApi.me();if(!String(session.role||'').includes('ADMIN')&&!['SUPERADMIN','RISK_ANALYST','DOCUMENT_ANALYST','SUPPORT_AGENT'].includes(session.role))throw new Error('FORBIDDEN');await loadAll();render('dashboard')}catch{loginScreen()}}
bootstrap();
