import './styles.css';
import './ui.css';
import { api, ApiError } from './api';

type View='home'|'today'|'clients'|'new-loan'|'portfolio'|'account';
const app=document.querySelector<HTMLDivElement>('#app')!;
let session:any=null;
let dashboard:any=null;
let loans:any[]=[];
let selectedPerson:any=null;

const nav:Array<[View,string,string]>=[['home','Inicio','⌂'],['today','Hoy','✓'],['clients','Clientes','◎'],['portfolio','Cartera','▦'],['account','Cuenta','●']];
const brl=(minor:number=0)=>(minor/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]!));
const errorText=(e:unknown)=>e instanceof ApiError?`${e.message}${e.requestId?` · ${e.requestId}`:''}`:'No fue posible completar la operación.';
const documentOptions=`<option value="CPF">CPF de Brasil</option><option value="RNM">RNM</option><option value="CEDULA_CO">Cédula de ciudadanía · Colombia</option><option value="CEDULA_VE">Cédula de identidad · Venezuela</option>`;

function authScreen(message=''){
  app.innerHTML=`<div class="auth-page"><section class="auth-brand"><div class="auth-logo">CB</div><p class="eyebrow">CLAVOS BRASIL</p><h1>Tu cartera,<br>todos los días.</h1><p>Controla cobros, clientes y créditos desde una sola operación.</p><div class="auth-points"><span>Consulta de historial</span><span>Cobros diarios</span><span>Control de cartera</span></div></section><main class="auth-main"><div class="auth-card"><div class="auth-card-head"><span>ACCESO</span><h2>Entrar a mi ruta</h2><p>Usa el documento con el que registraste tu cuenta.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<form id="loginForm"><label>Tipo de documento<select id="documentType" required>${documentOptions}</select></label><label>Número de documento<input id="documentNumber" autocomplete="username" placeholder="Número sin puntos ni espacios" required></label><label>Código de acceso<input id="accessCode" type="password" autocomplete="current-password" placeholder="Tu código de acceso" required></label><button class="primary">Ingresar</button></form><div class="auth-divider"><span>¿Primera vez?</span></div><button type="button" class="secondary auth-secondary" id="showRegister">Crear mi cuenta</button></div></main></div>`;
  document.querySelector<HTMLFormElement>('#loginForm')!.onsubmit=async e=>{e.preventDefault();try{session=await api.login(document.querySelector<HTMLSelectElement>('#documentType')!.value,document.querySelector<HTMLInputElement>('#documentNumber')!.value,document.querySelector<HTMLInputElement>('#accessCode')!.value);await loadCore();render('home')}catch(error){authScreen(errorText(error))}};
  document.querySelector<HTMLButtonElement>('#showRegister')!.onclick=()=>registerScreen();
}

function registerScreen(message=''){
  app.innerHTML=`<div class="auth-page register-page"><section class="auth-brand"><div class="auth-logo">CB</div><p class="eyebrow">NUEVA CUENTA</p><h1>Empieza con<br>lo esencial.</h1><p>Solo pedimos los datos necesarios para identificarte y ubicar tu ruta de trabajo.</p></section><main class="auth-main"><div class="auth-card register-card"><div class="auth-card-head"><span>REGISTRO</span><h2>Crear mi cuenta</h2><p>Datos personales y ubicación de tu ruta. Nada más.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<form id="registerForm"><label>Nombre completo<input name="full_name" autocomplete="name" placeholder="Ej.: Carlos Alberto Mendoza" required></label><div class="twocol"><label>Documento<select name="document_type" required>${documentOptions}</select></label><label>Número<input name="document_number" autocomplete="off" placeholder="Número del documento" required></label></div><label>Fecha de nacimiento<input name="birth_date" type="date" required></label><div class="twocol"><label>Estado donde estás<input name="route_state" placeholder="Ej.: Pernambuco" required></label><label>Ciudad de actuación de la ruta<input name="route_city" placeholder="Ej.: Recife" required></label></div><button class="primary">Crear cuenta</button><button type="button" class="secondary auth-secondary" id="backLogin">Ya tengo cuenta</button></form><p class="privacy-note">Tu documento identifica la cuenta. No funciona como contraseña.</p></div></main></div>`;
  document.querySelector<HTMLButtonElement>('#backLogin')!.onclick=()=>authScreen();
  const form=document.querySelector<HTMLFormElement>('#registerForm')!;
  form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);try{session=await api.register(Object.fromEntries(fd.entries()));const code=session.access_code;app.innerHTML=`<div class="auth-page"><section class="auth-brand"><div class="auth-logo">CB</div><p class="eyebrow">CUENTA CREADA</p><h1>Tu ruta está lista.</h1><p>Guarda tu código antes de continuar.</p></section><main class="auth-main"><div class="auth-card access-created"><div class="auth-card-head"><span>CÓDIGO DE ACCESO</span><h2>Guárdalo ahora</h2><p>Lo necesitarás junto con tu documento para volver a entrar.</p></div><div class="access-code">${esc(code)}</div><button class="primary" id="continueApp">Continuar a mi cartera</button><p class="privacy-note">Por seguridad, este código no volverá a mostrarse completo.</p></div></main></div>`;document.querySelector<HTMLButtonElement>('#continueApp')!.onclick=async()=>{await loadCore();render('home')}}catch(error){registerScreen(errorText(error))}};
}

function shell(view:View,content:string){return `<div class="phone"><header><div class="brand"><div class="logo">CB</div><div><b>Clavos Brasil</b><small>${esc(session?.user?.full_name||'Mi ruta')}</small></div></div><button class="avatar" data-view="account">${esc((session?.user?.full_name||'CB').split(' ').slice(0,2).map((x:string)=>x[0]).join(''))}</button></header><main>${content}</main><nav>${nav.map(([id,label,icon])=>`<button data-view="${id}" class="${view===id?'active':''}"><i>${icon}</i>${label}</button>`).join('')}</nav></div>`}
async function loadCore(){const [d,l]=await Promise.all([api.dashboard(),api.loans()]);dashboard=d;loans=l.items||[]}
function home(){const p=dashboard?.portfolio||{},c=dashboard?.collections_today||{},pending=Math.max(0,(c.expected_minor||0)-(c.received_minor||0));return `<section class="hero"><p class="eyebrow">MI CARTERA</p><h1>Estado de la operación.</h1><p>Datos cargados desde la API de tu organización.</p></section><div class="balance"><small>Capital en circulación</small><h2>${brl(p.principal_minor)}</h2><div><span>Créditos activos <b>${p.active_loans||0}</b></span><span>Total contractual <b>${brl(p.contractual_total_minor)}</b></span></div></div><div class="stats"><article><small>Previsto hoy</small><strong>${brl(c.expected_minor)}</strong><span>${c.installments_due||0} cuotas</span></article><article class="green"><small>Recibido</small><strong>${brl(c.received_minor)}</strong><span>${c.payments_count||0} pagos</span></article><article><small>Pendiente</small><strong>${brl(pending)}</strong><span>hoy</span></article><article><small>Cartera</small><strong>${p.active_loans||0}</strong><span>créditos</span></article></div><div class="section-head"><div><p class="eyebrow">ACCESOS RÁPIDOS</p><h3>Operación</h3></div></div><div class="actions"><button data-view="today"><i>✓</i><b>Cobros de hoy</b><span>Registrar pagos.</span></button><button data-view="clients"><i>⌕</i><b>Consultar cliente</b><span>Historial y score.</span></button><button data-view="new-loan"><i>+</i><b>Nuevo crédito</b><span>Registrar una operación.</span></button><button data-view="portfolio"><i>▦</i><b>Mi cartera</b><span>Créditos registrados.</span></button></div>`}
function portfolio(){return `<section class="hero compact"><p class="eyebrow">CARTERA</p><h1>Créditos registrados</h1><p>${loans.length} operaciones cargadas desde D1.</p></section><div class="list">${loans.length?loans.map(l=>`<article class="loan"><div><b>${esc(l.person_name)}</b><span>${esc(l.status)} · ${esc(l.frequency)}</span></div><div><b>${brl(l.principal_minor)}</b><span>Total ${brl(l.contractual_total_minor)}</span></div></article>`).join(''):'<div class="notice">Todavía no hay créditos registrados.</div>'}</div>`}
function today(){return `<section class="hero compact"><p class="eyebrow">PAGOS</p><h1>Registrar cobro</h1><p>Los pagos son append-only: un nuevo registro nunca sobrescribe uno anterior.</p></section><div class="list">${loans.map(l=>`<article class="person pay"><div class="initial">${esc(l.person_name?.slice(0,2))}</div><div class="person-info"><b>${esc(l.person_name)}</b><span>${esc(l.id)}</span></div><div class="right"><b>${brl(Math.round(l.contractual_total_minor/l.installment_count))}</b></div><button class="paybtn" data-pay="${esc(l.id)}">Registrar pago</button></article>`).join('')||'<div class="notice">No hay créditos disponibles.</div>'}</div>`}
function clientsView(){return `<section class="hero compact"><p class="eyebrow">CLIENTES</p><h1>Consultar cliente</h1><p>CPF, nombre, nacimiento y motivo son obligatorios.</p></section><form class="search-card" id="searchForm"><label>CPF<input name="cpf" placeholder="000.000.000-00" inputmode="numeric" required></label><label>Nombre completo<input name="full_name" placeholder="Ej.: José Antonio Pérez Gómez" required></label><label>Fecha de nacimiento<input name="birth_date" type="date" required></label><label>Motivo<select name="reason"><option value="ANALISIS_DE_CREDITO">Análisis de crédito</option><option value="NUEVA_OPERACION">Nueva operación</option></select></label><button class="primary">Consultar en Clavos Brasil</button></form><div id="clientResult"></div>`}
function showPersonResult(result:any){const box=document.querySelector<HTMLDivElement>('#clientResult')!;if(!result.found){box.innerHTML=`<div class="profile"><h2>Sin coincidencia verificada</h2><p>No existe un perfil que coincida exactamente con CPF, nombre y nacimiento.</p><button class="primary" id="createFromSearch">Registrar esta persona</button></div>`;document.querySelector<HTMLButtonElement>('#createFromSearch')!.onclick=()=>createPersonFromSearch();return}selectedPerson=result.person;const s=result.score;box.innerHTML=`<div class="profile"><div class="profile-top"><div><span class="verified">● ${esc(result.person.identity_status)}</span><h2>${esc(result.person.full_name)}</h2><small>${esc(result.person.cpf_masked)} · ${esc(result.person.city||'')}</small></div><div class="score"><b>${s?.value??'—'}</b><span>/1000</span></div></div><div class="rating"><span>Clasificación</span><b>${esc(s?.rating||'SIN HISTORIAL')}</b><em>${esc(s?.confidence||'SIN CONFIANZA')}</em></div><button class="primary" data-view="new-loan">Registrar nuevo crédito</button></div>`;wireNavigation()}
async function createPersonFromSearch(){const form=document.querySelector<HTMLFormElement>('#searchForm')!,fd=new FormData(form);try{selectedPerson=await api.createPerson({cpf:fd.get('cpf'),full_name:fd.get('full_name'),birth_date:fd.get('birth_date')});render('new-loan')}catch(error){alert(errorText(error))}}
function newLoan(){if(!selectedPerson)return `<section class="hero compact"><p class="eyebrow">NUEVO CRÉDITO</p><h1>Selecciona primero un cliente</h1><p>Por seguridad, el crédito debe estar vinculado a una persona identificada.</p></section><button class="primary" data-view="clients">Consultar cliente</button>`;return `<section class="hero compact"><p class="eyebrow">NUEVO CRÉDITO</p><h1>Registrar operación</h1><p>${esc(selectedPerson.full_name)} · ${esc(selectedPerson.identity_status)}</p></section><form class="form-card" id="loanForm"><label>Capital entregado<div class="moneyinput"><span>R$</span><input id="principal" value="3000" inputmode="decimal"></div></label><div class="twocol"><label>Número de cuotas<input id="count" value="30" type="number" min="1" max="366"></label><label>Valor por cuota<div class="moneyinput"><span>R$</span><input id="installment" value="130" inputmode="decimal"></div></label></div><label>Periodicidad<select id="frequency"><option value="DAILY">Diaria</option><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensual</option></select></label><label>Fecha de entrega<input id="disbursed" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Primera fecha de cobro<input id="firstDue" type="date" required></label><div class="summary"><div><span>Capital</span><b id="summaryPrincipal"></b></div><div><span>Total previsto</span><b id="summaryTotal"></b></div><div><span>Costo financiero total</span><b id="summaryCost"></b></div><div><span>Carga sobre el capital</span><b id="summaryRate"></b></div></div><label>Documento de identidad<input id="identityFile" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required></label><label>Tipo de documento<select id="docType"><option value="RG">RG</option><option value="CNH">CNH</option><option value="OTHER">Otro documento oficial</option></select></label><label>Evidencia de la operación<input id="evidenceFile" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"></label><div class="notice">Los documentos se almacenan en R2 privado y quedan pendientes de revisión interna. El costo total de la operación permanece visible.</div><button class="primary">Crear crédito y enviar documentos</button></form>`}
function account(){return `<section class="hero compact"><p class="eyebrow">CUENTA</p><h1>${esc(session?.user?.full_name||'Cuenta')}</h1><p>Rol: ${esc(session?.role||'')}</p></section><div class="account-card"><div class="account-row"><span>Cuenta</span><b>${esc(session?.user?.full_name||'')}</b></div><div class="account-row"><span>Ruta</span><b>${esc(session?.organization_id||'')}</b></div></div><button class="secondary" id="refreshData">Actualizar datos</button><button class="secondary" id="logout">Cerrar sesión</button>`}
async function submitLoan(){const p=Number((document.querySelector<HTMLInputElement>('#principal')!.value||'0').replace(',','.')),n=Number(document.querySelector<HTMLInputElement>('#count')!.value),q=Number((document.querySelector<HTMLInputElement>('#installment')!.value||'0').replace(',','.')),total=n*q;try{const loan=await api.createLoan({person_id:selectedPerson.id,principal_minor:Math.round(p*100),contractual_total_minor:Math.round(total*100),disbursed_at:document.querySelector<HTMLInputElement>('#disbursed')!.value,first_due_date:document.querySelector<HTMLInputElement>('#firstDue')!.value,installment_count:n,frequency:document.querySelector<HTMLSelectElement>('#frequency')!.value});const idFile=document.querySelector<HTMLInputElement>('#identityFile')!.files?.[0];if(idFile){const f=new FormData();f.append('file',idFile);f.append('person_id',selectedPerson.id);f.append('loan_id',loan.id);f.append('document_type',document.querySelector<HTMLSelectElement>('#docType')!.value);f.append('document_role','IDENTITY');await api.uploadDocument(f)}const evidence=document.querySelector<HTMLInputElement>('#evidenceFile')!.files?.[0];if(evidence){const f=new FormData();f.append('file',evidence);f.append('person_id',selectedPerson.id);f.append('loan_id',loan.id);f.append('document_type','OPERATION_EVIDENCE');f.append('document_role','LOAN_EVIDENCE');await api.uploadDocument(f)}await loadCore();selectedPerson=null;render('portfolio');alert('Crédito creado y documentos enviados a revisión.')}catch(error){alert(errorText(error))}}
function wireNavigation(){document.querySelectorAll<HTMLElement>('[data-view]').forEach(x=>x.onclick=()=>render(x.dataset.view as View))}
function wireView(view:View){wireNavigation();if(view==='clients'){const searchForm=document.querySelector<HTMLFormElement>('#searchForm')!;searchForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(searchForm);try{showPersonResult(await api.searchPerson(Object.fromEntries(fd.entries())))}catch(error){document.querySelector('#clientResult')!.innerHTML=`<div class="notice">${esc(errorText(error))}</div>`}}}if(view==='new-loan'&&selectedPerson){const form=document.querySelector<HTMLFormElement>('#loanForm')!;const calc=()=>{const p=Number((document.querySelector<HTMLInputElement>('#principal')!.value||'0').replace(',','.')),n=Number(document.querySelector<HTMLInputElement>('#count')!.value||0),q=Number((document.querySelector<HTMLInputElement>('#installment')!.value||'0').replace(',','.')),total=n*q,cost=total-p,rate=p?cost/p*100:0;document.querySelector('#summaryPrincipal')!.textContent=brl(Math.round(p*100));document.querySelector('#summaryTotal')!.textContent=brl(Math.round(total*100));document.querySelector('#summaryCost')!.textContent=brl(Math.round(cost*100));document.querySelector('#summaryRate')!.textContent=rate.toFixed(1).replace('.',',')+'%'};form.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));calc();form.onsubmit=e=>{e.preventDefault();void submitLoan()}}if(view==='today')document.querySelectorAll<HTMLElement>('[data-pay]').forEach(x=>x.onclick=async()=>{const raw=prompt('Valor recibido en R$');if(!raw)return;const amount=Math.round(Number(raw.replace(',','.'))*100);if(!amount)return;try{await api.recordPayment(x.dataset.pay!,{amount_minor:amount,paid_at:new Date().toISOString(),method:'CASH'});await loadCore();render('today')}catch(error){alert(errorText(error))}});if(view==='account'){document.querySelector<HTMLButtonElement>('#logout')!.onclick=async()=>{await api.logout().catch(()=>null);session=null;authScreen()};document.querySelector<HTMLButtonElement>('#refreshData')!.onclick=async()=>{await loadCore();render('home')}}}
function render(view:View){let content='';if(view==='home')content=home();if(view==='today')content=today();if(view==='clients')content=clientsView();if(view==='new-loan')content=newLoan();if(view==='portfolio')content=portfolio();if(view==='account')content=account();app.innerHTML=shell(view==='new-loan'?'home':view,content);wireView(view)}
async function bootstrap(){try{session=await api.me();await loadCore();render('home')}catch{authScreen()}}
void bootstrap();
