import './styles.css';

type View='home'|'today'|'clients'|'new-loan'|'portfolio'|'team'|'account';
const app=document.querySelector<HTMLDivElement>('#app')!;

const clients=[
 {name:'José Antonio Pérez',business:'Mercado El Sol',score:872,rating:'LIMPIO',due:'R$ 130',status:'PENDIENTE'},
 {name:'María Fernanda Rojas',business:'Tienda Central',score:811,rating:'LIMPIO',due:'R$ 90',status:'PAGADO'},
 {name:'Luis Alberto Ramírez',business:'Barbería Luis',score:641,rating:'ATENCIÓN',due:'R$ 150',status:'PARCIAL'},
 {name:'Carlos Medina',business:'Bodega Caribe',score:424,rating:'CLAVO',due:'R$ 110',status:'ATRASADO'}
];

const nav:Array<[View,string,string]>=[['home','Inicio','⌂'],['today','Hoy','✓'],['clients','Clientes','◎'],['portfolio','Cartera','▦'],['account','Cuenta','●']];
const money=(v:string)=>`<strong>${v}</strong>`;
const status=(s:string)=>`<span class="badge ${s==='PAGADO'?'ok':s==='ATRASADO'?'bad':s==='PARCIAL'?'warn':''}">${s}</span>`;

function shell(view:View,content:string){return `<div class="phone">
<header><div class="brand"><div class="logo">CB</div><div><b>Clavos Brasil</b><small>Inversiones Mendoza</small></div></div><button class="avatar" data-view="account">CM</button></header>
<main>${content}</main>
<nav>${nav.map(([id,label,icon])=>`<button data-view="${id}" class="${view===id?'active':''}"><i>${icon}</i>${label}</button>`).join('')}</nav>
</div>`}

function home(){return `<section class="hero"><p class="eyebrow">MI CARTERA</p><h1>Buenas tardes, Carlos.</h1><p>Este es el estado de tu operación para hoy.</p></section>
<div class="balance"><small>Capital en circulación</small><h2>R$ 98.600</h2><div><span>Disponible <b>R$ 21.400</b></span><span>Por cobrar <b>R$ 126.300</b></span></div></div>
<div class="stats"><article><small>Previsto hoy</small>${money('R$ 4.870')}<span>47 cuotas</span></article><article class="green"><small>Recibido</small>${money('R$ 3.940')}<span>80,9%</span></article><article><small>Pendiente</small>${money('R$ 930')}<span>11 clientes</span></article><article><small>En mora</small>${money('3')}<span>clientes</span></article></div>
<div class="section-head"><div><p class="eyebrow">ACCESOS RÁPIDOS</p><h3>Operación</h3></div></div>
<div class="actions"><button data-view="today"><i>✓</i><b>Cobros de hoy</b><span>Registrar pagos pendientes.</span></button><button data-view="clients"><i>⌕</i><b>Consultar cliente</b><span>Historial y Clavos Score.</span></button><button data-view="new-loan"><i>+</i><b>Nuevo crédito</b><span>Registrar una operación.</span></button><button data-view="portfolio"><i>▦</i><b>Mi cartera</b><span>Créditos y rendimiento.</span></button></div>
<div class="section-head"><div><p class="eyebrow">PRÓXIMOS</p><h3>Cobros pendientes</h3></div><button data-view="today">Ver todos</button></div><div class="list">${clients.slice(0,3).map(clientRow).join('')}</div>`}

function clientRow(c:typeof clients[number]){return `<article class="person"><div class="initial">${c.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><div class="person-info"><b>${c.name}</b><span>${c.business} · Score ${c.score}</span></div><div class="right"><b>${c.due}</b>${status(c.status)}</div></article>`}

function today(){return `<section class="hero compact"><p class="eyebrow">08 SEP 2026</p><h1>Cobros de hoy</h1><p>47 cuotas · R$ 4.870 previstos</p></section><div class="progress-card"><div><span>Recibido hoy</span><b>R$ 3.940</b></div><div class="bar"><i style="width:80.9%"></i></div><small>80,9% del objetivo diario</small></div><div class="filter"><button class="selected">Pendientes 11</button><button>Pagados 31</button><button>Parciales 5</button></div><div class="list">${clients.map(c=>`<article class="person pay"><div class="initial">${c.name.split(' ')[0][0]}${c.name.split(' ')[1][0]}</div><div class="person-info"><b>${c.business}</b><span>${c.name} · cuota de hoy</span></div><div class="right"><b>${c.due}</b>${status(c.status)}</div>${c.status!=='PAGADO'?`<button class="paybtn" data-pay="${c.name}">Registrar pago</button>`:''}</article>`).join('')}</div>`}

function clientsView(){return `<section class="hero compact"><p class="eyebrow">CLIENTES</p><h1>Buscar cliente</h1><p>Consulta antes de registrar una nueva operación.</p></section><div class="search-card"><label>CPF<input placeholder="000.000.000-00" inputmode="numeric"></label><label>Nombre completo<input placeholder="Ej.: José Antonio Pérez Gómez"></label><label>Fecha de nacimiento<input type="date"></label><button class="primary" id="demoSearch">Consultar en Clavos Brasil</button></div><div id="clientResult"></div>`}

function resultCard(){return `<div class="profile"><div class="profile-top"><div><span class="verified">● Identidad verificada</span><h2>José Antonio Pérez</h2><small>CPF •••.281.•••-42 · Recife/PE</small></div><div class="score"><b>872</b><span>/1000</span></div></div><div class="rating"><span>Clasificación</span><b>LIMPIO</b><em>CONFIANZA ALTA</em></div><div class="profile-grid"><div><b>4</b><span>créditos</span></div><div><b>94%</b><span>puntualidad</span></div><div><b>100%</b><span>finalizados</span></div><div><b>3 días</b><span>mayor retraso</span></div></div><button class="primary" data-view="new-loan">Registrar nuevo crédito</button></div>`}

function newLoan(){return `<section class="hero compact"><p class="eyebrow">NUEVO CRÉDITO</p><h1>Registrar operación</h1><p>El costo total debe quedar visible antes de confirmar.</p></section><form class="form-card" id="loanForm"><div class="step"><i>1</i><div><b>Cliente</b><span>José Antonio Pérez · Score 872</span></div></div><label>Capital entregado<div class="moneyinput"><span>R$</span><input id="principal" value="3000" inputmode="decimal"></div></label><div class="twocol"><label>Número de cuotas<input id="count" value="30" type="number"></label><label>Valor por cuota<div class="moneyinput"><span>R$</span><input id="installment" value="130" inputmode="decimal"></div></label></div><label>Periodicidad<select><option>Diaria</option><option>Semanal</option><option>Mensual</option></select></label><label>Primera fecha de cobro<input type="date" value="2026-09-09"></label><div class="summary"><div><span>Capital</span><b id="summaryPrincipal">R$ 3.000,00</b></div><div><span>Total previsto</span><b id="summaryTotal">R$ 3.900,00</b></div><div><span>Costo financiero total</span><b id="summaryCost">R$ 900,00</b></div><div><span>Carga sobre el capital</span><b id="summaryRate">30,0%</b></div></div><div class="notice">Clavos Brasil registra y gestiona operaciones declaradas. Los términos deben cumplir la legislación aplicable y no pueden utilizarse para ocultar el costo financiero real.</div><button class="primary">Continuar con documentación</button></form>`}

function portfolio(){return `<section class="hero compact"><p class="eyebrow">CARTERA</p><h1>Mi cartera</h1><p>Rendimiento y estado de los créditos registrados.</p></section><div class="stats portfolio"><article><small>Activos</small>${money('46')}<span>créditos</span></article><article><small>Capital</small>${money('R$ 98,6 mil')}<span>en circulación</span></article><article class="green"><small>Cobrado mes</small>${money('R$ 72,4 mil')}<span>entradas</span></article><article><small>Mora</small>${money('7,4%')}<span>de cartera</span></article></div><div class="section-head"><div><p class="eyebrow">CRÉDITOS</p><h3>Activos recientes</h3></div></div><div class="list">${clients.map(c=>`<article class="loan"><div><b>${c.business}</b><span>${c.name}</span></div><div><b>${c.due}/día</b><span>Saldo ${c.score>700?'R$ 1.560':'R$ 2.040'}</span></div></article>`).join('')}</div>`}

function account(){return `<section class="hero compact"><p class="eyebrow">CUENTA</p><h1>Inversiones Mendoza</h1><p>Recife, Pernambuco · Organización verificada.</p></section><div class="account-card"><div class="account-row"><span>Plan</span><b>Fundador · 6 meses gratis</b></div><div class="account-row"><span>Rol</span><b>Propietario</b></div><div class="account-row"><span>Equipo</span><b>6 usuarios</b></div><div class="account-row"><span>Cobradores</span><b>4 activos</b></div></div><button class="secondary" data-view="team">Administrar equipo</button><button class="secondary">Seguridad y acceso</button><button class="secondary">Soporte</button>`}

function render(view:View){let content='';if(view==='home')content=home();if(view==='today')content=today();if(view==='clients')content=clientsView();if(view==='new-loan')content=newLoan();if(view==='portfolio')content=portfolio();if(view==='account'||view==='team')content=account();app.innerHTML=shell(view==='new-loan'?'home':view,content);document.querySelectorAll<HTMLElement>('[data-view]').forEach(x=>x.onclick=()=>render(x.dataset.view as View));const search=document.querySelector('#demoSearch');if(search)search.addEventListener('click',()=>{document.querySelector('#clientResult')!.innerHTML=resultCard();document.querySelectorAll<HTMLElement>('[data-view]').forEach(x=>x.onclick=()=>render(x.dataset.view as View));});const form=document.querySelector<HTMLFormElement>('#loanForm');if(form){const calc=()=>{const p=Number((document.querySelector<HTMLInputElement>('#principal')?.value||'0').replace(',','.'));const n=Number(document.querySelector<HTMLInputElement>('#count')?.value||0);const q=Number((document.querySelector<HTMLInputElement>('#installment')?.value||'0').replace(',','.'));const total=n*q,cost=total-p,rate=p?cost/p*100:0;const br=(x:number)=>x.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});document.querySelector('#summaryPrincipal')!.textContent=br(p);document.querySelector('#summaryTotal')!.textContent=br(total);document.querySelector('#summaryCost')!.textContent=br(cost);document.querySelector('#summaryRate')!.textContent=rate.toFixed(1).replace('.',',')+'%'};form.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));form.onsubmit=e=>{e.preventDefault();alert('Flujo de documentación será conectado a la API y al almacenamiento privado R2.');}}document.querySelectorAll<HTMLElement>('[data-pay]').forEach(x=>x.onclick=()=>alert(`Registro de pago para ${x.dataset.pay}: la API creará un lanzamiento append-only, sin sobrescribir pagos anteriores.`));}
render('home');
